### ISSUE TITLE
Spooner doesn't work with FiveM

### ISSUE THREAD

**Issue by YesImSevy** [kibook/spooner#10]
Well for one the uiprompt doesn't even work for FiveM  please fix this or add me on discord Severingcastle8#8743 I need this to work for FiveM please.

**Comment by kibook** [comment]
The FiveM support is a brand new thing I just started working on, but the basic stuff does work in FiveM right now. Take a look in [fxmanifest.lua](https://github.com/kibook/spooner/blob/master/fxmanifest.lua) and you'll see I've placed two groups of metadata, one for RedM and one for FiveM. Currently, to get it working in FiveM, comment out the RedM section and uncomment the FiveM section. I'm hoping to find a more elegant way to handle this in the future.

**Comment by YesImSevy** [comment]
> The FiveM support is a brand new thing I just started working on, but the basic stuff does work in FiveM right now. Take a look in [fxmanifest.lua](https://github.com/kibook/spooner/blob/master/fxmanifest.lua) and you'll see I've placed two groups of metadata, one for RedM and one for FiveM. Currently, to get it working in FiveM, comment out the RedM section and uncomment the FiveM section. I'm hoping to find a more elegant way to handle this in the future.

I have done this already but it still doesn't seam to work at all. I will try again and see if anything is different.

**Comment by kibook** [comment]
What error messages do you receive when starting the resource?

**Comment by YesImSevy** [comment]
> What error messages do you receive when starting the resource?

Not getting any at all. Just not working I've given myself permissions for it aswell. I'll try on a new server to just see if its something on my setup I currently have.

**Comment by YesImSevy** [comment]
I really need to get this working :( I don't know what Im doing wrong I've added the permissions to people and tried a fresh install of the resource with what you told me to do in the fxmanifest.lua but it still doesn't work. I want to be able to use this with my friends tonight when we play.

**Comment by kibook** [comment]
Could you share screenshots of the server console and client console when starting the resource? To make sure there's not any errors appearing in there.

When you say it's not working, what have you tried exactly? Entering spooner mode with the Delete key? Have you tried using the /spooner command instead to see if the issue is the control?

**Comment by YesImSevy** [comment]
> Could you share screenshots of the server console and client console when starting the resource? To make sure there's not any errors appearing in there.
> 
> When you say it's not working, what have you tried exactly? Entering spooner mode with the Delete key? Have you tried using the /spooner command instead to see if the issue is the control?

I feel very dumb now I thought F to open the menu for spawning stuff and using it sorry for wasting your time...

**Comment by kibook** [comment]
No problem! There are a few control changes I have to document for FiveM, because not every default key in RedM has a matching default key in FiveM. F1 currently opens the Save DB menu, for example, not J. For now, refer to https://docs.fivem.net/docs/game-references/controls for what the default keys are for the control numbers in [config.lua](https://github.com/kibook/spooner/blob/master/config.lua).

**Comment by YesImSevy** [comment]
> No problem! There are a few control changes I have to document for FiveM, because not every default key in RedM has a matching default key in FiveM. F1 currently opens the Save DB menu, for example, not J. For now, refer to https://docs.fivem.net/docs/game-references/controls for what the default keys are for the control numbers in [config.lua](https://github.com/kibook/spooner/blob/master/config.lua).

Hey when deleting existing probs/objects in the game how would I go about making it show for others aswell?

**Comment by kibook** [comment]
Props spawned as part of the map are not networked, so every player has their own, separate local copy of them. You could try using Register as Networked in the properties menu of the object before deleting it, but I'm not sure if that would actually work. It might just register your copy of the object as networked but not affect other player's copies, so they'd just see a duplicate object appear on top of their copy and then get deleted.

You may not even be able to register those props as networked. You'll know if it worked if the object gets a number in square brackets `[ ]` in its properties, that is its network ID. If it doesn't have a number in square brackets, it is not networked and so changes to it will not be synchronized with other players.

At worst you will just have to tell other players to delete the object on their ends as well.

**Comment by YesImSevy** [comment]
> Props spawned as part of the map are not networked, so every player has their own, separate local copy of them. You could try using Register as Networked in the properties menu of the object before deleting it, but I'm not sure if that would actually work. It might just register your copy of the object as networked but not affect other player's copies, so they'd just see a duplicate object appear on top of their copy and then get deleted.
> 
> You may not even be able to register those props as networked. You'll know if it worked if the object gets a number in square brackets `[ ]` in its properties, that is its network ID. If it doesn't have a number in square brackets, it is not networked and so changes to it will not be synchronized with other players.
> 
> At worst you will just have to tell other players to delete the object on their ends as well.

Yea that actually does work. With saving things how can I just save everything I've placed/changed and then load it in later it is a bit confusing.

**Comment by kibook** [comment]
Press F1 in FiveM (for now) to open the Save DB menu (the help/docs say J, that's for RedM, there's no control bound to J by default in FiveM though). Then, enter a name in the text field and click Save. You can then click that name in the saved DB list to load all the placements back into your current DB.

**Comment by kibook** [comment]
Here's a video example: https://streamable.com/cj3sng
