### ISSUE TITLE
 I can't open the menu

### ISSUE THREAD

**Issue by B0biD0ng** [kibook/spooner#17]
![image](https://user-images.githubusercontent.com/81963237/135119729-0c9a27d3-a0c2-40f9-84fd-72fe93e90a69.png)
![image](https://user-images.githubusercontent.com/81963237/135119829-d3416187-f829-46c5-896f-0730f652dee0.png)

I prepared the menu according to the tutorial, but anyway, when I write / spooner in the game, nothing happens and I can spam as much as I want and anyway, nothing happens.

**Comment by kibook** [comment]
`path/to/spooner/permissions.cfg` is just an example path. You have to adjust it based on where exactly you installed the spooner resource:

> 3. Add the following to server.cfg:
>
> ```
> exec path/to/spooner/permissions.cfg
> ensure spooner
> ```
> 
> **The path to permissions.cfg depends on where in the resources directory the resource is installed.**

So if you placed the folder in `resources/[local]`, then it should be `exec resources/[local]/spooner/permissions.cfg`. If you installed it directly in the `resources` folder, then it would be `exec resources/spooner/permissions.cfg` instead.

**Comment by Aspry1** [comment]
I'am having the exact same problem.

i have the folder spooner on my dev Server.
i changed the path for permission.cfg
spooner runs as ensure

but ingame command /spooner wont work :O

**Comment by Aspry1** [comment]
IDK why but i had an Folder with [Name] after executing the permissions.cfg on the same folder wher the resources.cfg is exec worked. So now it works on my original file path. idk why it help someone
