### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by BBDMAC** [kibook/spooner#21]
Hey there I am receiving an error when loading spooner script - I do have UIPROMPT installed as directed and I am being thrown the following error with installed as seen also.

Any help would be amazing thank you!
![uiprompt](https://user-images.githubusercontent.com/30957407/142760957-e995bd83-870d-43e3-85b4-888d09d2a281.png)

**Comment by kibook** [comment]
Is this for RedM or FiveM?

Did you modify anything in fxmanifest.lua aside from setting the gameName variable?

Are there any errors in the server console (not the in-game one) when uiprompt starts?

**Comment by BBDMAC** [comment]
no errors in console
 
![fx](https://user-images.githubusercontent.com/30957407/142765175-2e2d7cd4-1e75-4dfd-b704-6934507ada7a.png)


REDM

**Comment by kibook** [comment]
You need to set the `gameName` variable, not the `game` metadata directly:

```lua
-- Set this to one of the following:
-- FiveM: "gta5"
-- RedM: "rdr3"
local gameName = ""
```

Inside the quotes, add either `gta5` (for FiveM) or `rdr3` (for RedM):
```lua
local gameName = "rdr3"
```

The `gameName` variable is used in a few places inside fxmanifest.lua to load different things for FiveM vs. RedM. Leaving it unset or removing it will cause issues like this. Unfortunately, this is the best method I've been able to find so far to have a single resource that loads different scripts for both games. There doesn't appear to be any way to automatically detect which game a resource is being used on within fxmanifest.lua.

**Comment by nickwayman1068** [comment]
Hello I have spooner installed and It will not open even when I have the dependency and spooner both started on the console any reason this might not be working?
