### ISSUE TITLE
What?!

### ISSUE THREAD

**Issue by ShaAlexander** [kibook/spooner#22]
You tell us in the readme that we need a requirement but that one seems RedM only, so now what? Can you be more clear please!

**Comment by kibook** [comment]
Absolutely. The `uiprompt` library is only used if you're running spooner on RedM. It is not required for FiveM at this time. I'll update the README to include this information, too.

**Comment by ShaAlexander** [comment]
Phew thanks for clearing out this question! I almost thought I where missing something…
