### ISSUE TITLE
[QUESTION] Doors

### ISSUE THREAD

**Issue by Ktos93** [kibook/spooner#25]
Is there way to make doors can be opened? Switch some options or something?

**Comment by TayMcKenzieNZ** [comment]
There should be an option called `static` or something, if you uncheck this, it makes it so it moves. It may even be called `dynamic`. I apologized, I haven't been on a redm / fivem server and used this in a few weeks, but from my understanding of Menyoo and their spooner, I would assume Kibook has used the same terminology.

Hope this helps! 😄

**Comment by Ktos93** [comment]
I cant find something like this.

**Comment by kibook** [comment]
I'm not aware of a way to make them work directly spawning them in spooner. While there isn't currently a way to toggle whether an entity is "dynamic" ([`SET_ENTITY_DYNAMIC`](https://vespura.com/doc/natives/?_0xFBFC4473F66CE344)), which is something I should add, making the door dynamic doesn't seem to make it function. There is a toggle for whether the entity is "frozen" ([`FREEZE_ENTITY_POSITION`](https://vespura.com/doc/natives/?_0x7D9EFB7AD6B19754)), but unfreezing the door seems to just cause it to fall through the ground when you attempt to interact with it.

The only way I've noticed to make a door work is to unfreeze it, export it as part of a ymap, and then stream said ymap. In that case, the door spawned via the ymap will open and close normally.

**Comment by Ktos93** [comment]
Thanks!
